Add health check on socket in StreamClientSink.
LibertyAces/BitSwanPump pull request #108
Opened 2021-03-04 15:11 UTC by PremyslCerny

2021-03-04 15:12 UTC, PremyslCerny commented
@ateska Please evaluate if the concept is correct. Thank you.

2021-03-04 17:17 UTC, ateska requested changes

2021-03-04 17:17 UTC, ateska commented on bspump/ipc/stream_client_sink.py
> +					sock.send(b"")
You cannot send data over the socket. This is not a good direction.

2021-03-09 10:34 UTC, PremyslCerny reviewed
Hotfix

2021-03-09 10:34 UTC, merged