Refactor KafkaSink
LibertyAces/BitSwanPump pull request #205
Opened 2024-07-25 11:51 UTC by mejroslav

2024-07-25 15:10 UTC, PremyslCerny reviewed
Please add comments to each change, like why we need the on tick etc.

2024-07-26 08:23 UTC, PremyslCerny commented on bspump/kafka/sink.py
> +	def _kafka_poll(self):
Add unthrottle back to kafka_poll.

2024-07-30 08:46 UTC, ateska requested changes
Change in the comment.

Also, please test a throughput before merging.

2024-07-30 08:46 UTC, ateska commented on bspump/kafka/sink.py
> +		# Custom options
Options that are not for librdkafka ...

2024-12-11 10:03 UTC, closed without merging