Include source ID to logging
LibertyAces/BitSwanPump pull request #206
Opened 2024-09-09 15:30 UTC by mejroslav

Logging now contains ID of the source in `struct_data` to make debugging much easier in case there are multiple TCP/UDP sources.

2024-09-09 15:38 UTC, PremyslCerny commented
Needs to be tested with many disconnecting/connecting clients so that there is a reasonable amount of logs at all circumstances

2024-09-10 09:22 UTC, mejroslav commented
> Needs to be tested with many disconnecting/connecting clients so that there is a reasonable amount of logs at all circumstances

Like this? :)

```
10-Sep-2024 09:04:41.219791 NOTICE bspump.ipc.stream_server_source [sd id="TCP-vmware-vsphere-10030" peer="10.161.201.10 51008"] Disconnected.
10-Sep-2024 09:06:11.125571 NOTICE bspump.ipc.stream_server_source [sd id="TCP-vmware-vsphere-10030" peer="10.161.201.10 33110"] Connected.
10-Sep-2024 09:06:11.127710 ERROR bspump.ipc.stream_server_source [sd id="TCP-vmware-vsphere-10030"] Error when handling client socket.

10-Sep-2024 09:06:11.128804 NOTICE bspump.ipc.stream_server_source [sd id="TCP-vmware-vsphere-10030" peer="10.161.201.10 33110"] Disconnected.
10-Sep-2024 09:07:41.217166 NOTICE bspump.ipc.stream_server_source [sd id="TCP-vmware-vsphere-10030" peer="10.161.201.10 44574"] Connected.
10-Sep-2024 09:07:41.218780 ERROR bspump.ipc.stream_server_source [sd id="TCP-vmware-vsphere-10030"] Error when handling client socket.

10-Sep-2024 09:07:41.219907 NOTICE bspump.ipc.stream_server_source [sd id="TCP-vmware-vsphere-10030" peer="10.161.201.10 44574"] Disconnected.
10-Sep-2024 09:09:11.126727 NOTICE bspump.ipc.stream_server_source [sd id="TCP-vmware-vsphere-10030" peer="10.161.201.10 46762"] Connected.
10-Sep-2024 09:09:11.128166 ERROR bspump.ipc.stream_server_source [sd id="TCP-vmware-vsphere-10030"] Error when handling client socket.

10-Sep-2024 09:09:11.129247 NOTICE bspump.ipc.stream_server_source [sd id="TCP-vmware-vsphere-10030" peer="10.161.201.10 46762"] Disconnected.
10-Sep-2024 09:10:41.217675 NOTICE bspump.ipc.stream_server_source [sd id="TCP-vmware-vsphere-10030" peer="10.161.201.10 48706"] Connected.
10-Sep-2024 09:10:41.219235 ERROR bspump.ipc.stream_server_source [sd id="TCP-vmware-vsphere-10030"] Error when handling client socket.

10-Sep-2024 09:10:41.220316 NOTICE bspump.ipc.stream_server_source [sd id="TCP-vmware-vsphere-10030" peer="10.161.201.10 48706"] Disconnected.
10-Sep-2024 09:12:11.128904 NOTICE bspump.ipc.stream_server_source [sd id="TCP-vmware-vsphere-10030" peer="10.161.201.10 44004"] Connected.
10-Sep-2024 09:12:11.130785 ERROR bspump.ipc.stream_server_source [sd id="TCP-vmware-vsphere-10030"] Error when handling client socket.

10-Sep-2024 09:12:11.131398 NOTICE bspump.ipc.stream_server_source [sd id="TCP-vmware-vsphere-10030" peer="10.161.201.10 44004"] Disconnected.
10-Sep-2024 09:13:41.219427 NOTICE bspump.ipc.stream_server_source [sd id="TCP-vmware-vsphere-10030" peer="10.161.201.10 40576"] Connected.
10-Sep-2024 09:13:41.220814 ERROR bspump.ipc.stream_server_source [sd id="TCP-vmware-vsphere-10030"] Error when handling client socket.

10-Sep-2024 09:13:41.221699 NOTICE bspump.ipc.stream_server_source [sd id="TCP-vmware-vsphere-10030" peer="10.161.201.10 40576"] Disconnected. 
```

2024-09-13 16:28 UTC, ateska requested changes

2024-09-13 16:28 UTC, ateska commented on bspump/ipc/protocol.py
> +			L.warning("Cannot decode line, replacing malformed data with backslash escape sequence: {}".format(err))
Don't log warnings in the "main" processing pipeline, this will only overflow logs.

2024-10-07 19:38 UTC, ateska approved these changes

2024-12-11 10:03 UTC, merged