Move context check from expression to a separate class.
LibertyAces/BitSwanPump pull request #95
Opened 2020-12-15 14:06 UTC by PremyslCerny

@ateska Please see

2020-12-15 16:24 UTC, ateska requested changes

2020-12-15 16:24 UTC, ateska commented on bspump/declarative/expression/datastructs/itemexpr.py
> +			return context.get(self.Key, self.Default)
You don't want to have this `if` here ... which means that this needs to be two classes you specialises into.

2020-12-15 16:24 UTC, ateska commented on bspump/declarative/expression/datastructs/itemexpr.py
> -				return self.evaluate_CONTEXT(with_dict, item)
`evaluate_CONTEXT` method needs to be removed.

2020-12-15 16:43 UTC, PremyslCerny commented
@ateska One more try. :)

2021-01-04 19:27 UTC, ateska approved these changes

2021-01-05 10:10 UTC, merged